import React from 'react';
export default function Hero({t,onNavigate}) {
 const data=t.json_data;
 return <section className="hero" id="hero"><div className="wrap hero-grid">
  <div className="hero-copy reveal"><div className="eyebrow animate-float">GET /pedro HTTP/1.1</div><p className="hero-kicker">{t.hero_kicker}</p><h1>Pedro Henrique <span>Peixoto</span></h1><div className="role">{t.hero_role} <span className="sep">/</span> C# · .NET · APIs</div><p className="lede">{t.hero_lede}</p>
   <div className="cta-row"><button className="btn btn-primary" onClick={()=>onNavigate('projetos')}>{t.btn_view_projects}</button><button className="btn btn-ghost" onClick={()=>onNavigate('contato')}>{t.btn_talk}</button><a className="text-link" href="https://github.com/pedroalmeidapeixoto" target="_blank" rel="noopener">GitHub ↗</a><a className="text-link" href="https://linkedin.com/in/pedroalmeidapeixoto" target="_blank" rel="noopener">LinkedIn ↗</a></div>
   <div className="hero-status-row"><span className="status-chip"><span className="pulse-dot"></span>{t.hero_status}</span><span className="mono-muted">{t.location_brazil} · UTC−3</span></div>
  </div>
  <div className="hero-side reveal reveal-delay"><div className="console glass-panel"><div className="console-bar"><span className="cdot"></span><span className="cdot"></span><span className="cdot"></span><span className="fname">pedro.dev — zsh</span><span className="console-code">200</span></div><div className="console-body"><div className="req"><span className="m">GET</span> /api/v1/pedro?full=true</div><div className="console-line">{t.console_response}</div><pre className="json">{JSON.stringify(Object.fromEntries(data.map(([k,v])=>[k.replaceAll('"',''),v.replace(/^"|"$/g,'' )])),null,2)}</pre></div></div>
   <div className="hero-mini-grid"><div className="mini-stat"><span className="k">{t.mini_focus}</span><strong>C# / .NET</strong></div><div className="mini-stat"><span className="k">{t.mini_core}</span><strong>APIs · SQL</strong></div><div className="mini-stat"><span className="k">{t.mini_approach}</span><strong>{t.mini_value}</strong></div><div className="mini-stat"><span className="k">{t.mini_location}</span><strong>{t.location_brazil}</strong></div></div>
  </div></div><button className="hero-scroll-arrow" onClick={()=>onNavigate('sobre')} aria-label={t.aria_scroll_about}><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 5v14M19 12l-7 7-7-7"/></svg></button></section>;
}
